apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nayeemnishaat/client # Important: Don't specify image tag.
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/*"
            dest: .
    - image: nayeemnishaat/comment
      context: comment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nayeemnishaat/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nayeemnishaat/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nayeemnishaat/post
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nayeemnishaat/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
