apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
  # labels:
  #   app: post-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: nayeemnishaat/post:latest
          imagePullPolicy: Never
