apiVersion: v1
kind: Pod
metadata:
  name: post
spec:
  containers:
    - name: post
      image: nayeemnishaat/post:latest
      imagePullPolicy: Never
#kubectl get pods  --watch # Watch the status of  pods
